### ISSUE TITLE
Dependencies throws an error when Publishing the extension

### ISSUE THREAD

**Issue by crisnicolas** [Microsoft/AL#1349]
I have an extension that is working fine and can be published correctly.

I define a dependency on the app.json file like this:

`  "dependencies": [{ "appId": "87c98f21-2470-4659-b032-f615d26b22cc",
                      "name": "MAIM Lots",
                      "publisher": "ClipDynamics",
                      "version": "1.0.0.0"
                    }],`

The system prompts me to download the symbols and I see that the symbols for the dependent extension have been downloaded.

If I try to Publish the extension now, without even having used the data created by the dependent extension, I get this error:

`Microsoft (R) AL Compiler version 0.12.15355
Copyright (C) Microsoft Corporation. All rights reserved

error AL0999: Internal error: 'Se han producido uno o varios errores.', Stack trace=unknown
Error: The package could not be created.`

**Comment by DominikDitoIvosevic** [comment]
Hi @crisnicolas . I'm afraid we do not have enough information to know what is the issue. Could you try just building the extension without publishing it (just press ctrl+shift+B) and tell us if that also fails. 
How big is the dependant extension? Could you possibly try and isolate the code from the dependant extension which is causing problems? Could you post publicly here just the symbol file?

**Comment by crisnicolas** [comment]
Hi Dominic,

Thanks for your answer.
Building the extension without publishing generates the exact same error.

The dependant extension is pretty small. The .app file is 17KB.

I've deleted everything from the dependant extension, and left only the creation of fields that I need on the second extension. And now the second extension can be created and published.

Then I've added all the other objects to the first extension one by one, and I've been able to isolate the object that prevents the second extension from being build.

Now I'm trying to isolate the code within the object.

Thanks for the guidance.

Regards,
Cristina Nicolàs

**Comment by crisnicolas** [comment]
Hi Dominic,

If on the first extension I create a global var that is actually a Label, the first extension can be build and published, but the second extension cannot be build.

If I change the Label for a TextConst then it works fine.

My conclusion is that the error is produced by Labels created on the first extension.

Regards,
Cristina Nicolàs

**Comment by crisnicolas** [comment]
If the Label is created as a local variable of a procedure, it's ok. 
But if the Label is created as a global variable of the object the second extension cannot be build.

**Comment by DominikDitoIvosevic** [comment]
Hi @crisnicolas . We are aware of the bug with labels in dependant extensions and it has been fixed in the December release.

**Comment by DominikDitoIvosevic** [comment]
Hi @crisnicolas . Are you still experiencing this issue with a newer version of the compiler?

**Comment by DominikDitoIvosevic** [comment]
@crisnicolas I expect this to be fixed in the latest version of the compiler. If you have more issues please open a new issue.

**Comment by Sogaard464** [comment]
Hello @DominikDitoIvosevic 
I still get this error, when I use one of the Danish specific extension (Payment and Reconciliation Formats (DK)),
I should have the december version of the compiler, my error message is: 
Microsoft (R) AL Compiler version 0.12.15359
Copyright (C) Microsoft Corporation. All rights reserved

error AL0999: Internal error: 'Der opstod en eller flere fejl.', Stack trace=unknown
Error: The package could not be created.
