### ISSUE TITLE
Issue Downloading symbols from Cloud Sandbox

### ISSUE THREAD

**Issue by gunavs** [Microsoft/AL#1496]
Before logging a new issue please make sure to:
1) Read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)
2) Search if there is an existing issue for what you want to log. If it's closed you can reopen it and add your comments.
3) Use the latest Developer Preview release both the server part and the AL Language extension in VS Code (listed on the [repository home page](https://github.com/Microsoft/AL))
4) If you're not using the latest released version (or are using a private build drop that is newer) please provide the version number in the issue

To help us reproduce the issue and find the root please try to:
A) Attach a minimal set of AL code that causes the issue
B) If the error occurs on the server - copy/paste the server stack trace from the Event Viewer

**Comment by gunavs** [comment]
We signed up for a new sandbox account and followed the steps on Installing VS code, AL extension. When we download symbols though, we get this following error

[2018-01-24 20:38:09.20] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2018-01-24 20:38:09.21] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2018-01-24 20:38:10.21] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2018-01-24 20:38:10.47] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
 
This is our launch.json


    "version": "0.2.0",
    "configurations": [
        {
            "name": "Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "startupObjectId": 22
        },
       ]
}

and our app.json

{
  "id": "1d9aace8-4c99-4d48-bf4b-fbf6b4b97d49",
  "name": "HalALWorld",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

**Comment by gunavs** [comment]
We signed up for a new sandbox account and followed the steps on Installing VS code, AL extension. When we download symbols though, we get this following error

[2018-01-24 20:38:09.20] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2018-01-24 20:38:09.21] Sending request to https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2018-01-24 20:38:10.21] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2018-01-24 20:38:10.47] Could not download reference symbols. Please ensure that:

The correct server name and instance are specified in the launch.json file.
The correct application version is specified in the app.json file.
This is our launch.json

"version": "0.2.0",
"configurations": [
    {
        "name": "Microsoft cloud sandbox",
        "type": "al",
        "request": "launch",
        "startupObjectId": 22
    },
   ]
}

and our app.json

{
"id": "1d9aace8-4c99-4d48-bf4b-fbf6b4b97d49",
"name": "HalALWorld",
"publisher": "Default publisher",
"brief": "",
"description": "",
"version": "1.0.0.0",
"compatibilityId": "1.0.0.0",
"privacyStatement": "",
"EULA": "",
"help": "",
"url": "",
"logo": "",
"capabilities": [],
"dependencies": [],
"screenshots": [],
"platform": "11.0.0.0",
"application": "11.0.0.0",
"idRange": {
"from": 50100,
"to": 50149
}
}

**Comment by atoader** [comment]
We are aware of the issue.  It will eventually be resolved by updating the cloud sandboxes, but that will take some time. You can get around this by downgrading to the previous version of the VSCode extension. Can you contact CSS to get the old extension?

**Comment by gunavs** [comment]
How do we contact CSS?

**Comment by atoader** [comment]
Please, open a support request through the Office 365 channel or contact your local subsidiary to have it created for you. This request will be redirected to the appropriate CSS specialty to help you out with your sandbox.
All requests related to Dynamics products in mainstream support must be created to the CSS (Customer Support & Service) channel. Github, Yammer, and other communication or social platform are intended only to handle feature enhancement or for product still in preview and before GA (General Availability)

**Comment by dennisfrostlander** [comment]
The online sandboxes have been recently updated. Could you please try again to download the symbols?
In case it still does not work, please also consider to reset the sandbox environmet.
