### ISSUE TITLE
Report.SAVEAS is slow compared to equivalent Report.Execute

### ISSUE THREAD

**Issue by jngillard** [microsoft/AL#4536]
There was a previous issue opened with similar behavior, but it is closed.
https://github.com/Microsoft/AL/issues/3424

When I am trying to use the method Report.SAVEAS(), it works but it is really slow.

When I am running this code: 
TempBlob.Blob.CreateOutStream(MyOutstream);
 report.saveas(<ReportNumber>, ReportParam, ReportFormat::Pdf, MyOutstream);

<ReportNumber>=Any report you are trying.

This takes about a minute to return the result back to the TempBlob.
If I use this call instead, the report data is returned within 2 seconds.
report.Execute(<ReportNumber>, ReportParam);

I don’t believe the issue is with the ReportParam that I am using since the Report.Execute is using the same Report Param. 

I wanted to know why this call is so slow. 

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: CA Dynamics NAV 13.3 (27233)

**Comment by jngillard** [comment]
There is nothing special about how I setup file access. The container was created with the  new-navcontainer powershell script. I've noticed no slowness of disk access in the container.

**Comment by jngillard** [comment]
Also, I can confirm that this speed issue does not exist in a production business central tenant. I deployed the code to a customer and it's fast. So it appears this issue is only with my docker container.

**Comment by FSharpCSharp** [comment]
I can agree with that behavior as well. The execution is also much slower here on a super fast SSD system.

**Comment by kalberes** [comment]
This is by design. It is caused by the NetFx40_LegacySecurityPolicy server configuration being set to false in the server.config.
The AL language server in VSCode needs this setting in order that publishing, and debugging works.
The good news is that for the Spring release of BC this has been fixed.  This setting is not needed and both the language server and reporting will work as expected.

**Comment by jimmymcp** [comment]
Sorry, just want to be clear...

You are saying that there is a performance issue with using Report.SaveAs and RDLC in Business Central (Fall '18). We are still seeing this issue (terrible SaveAs PDF from RDLC performance, saving from Word layout is fine) in CU6. Is it right that the fix in Spring '19 release has not been ported to Fall '18? If so, will we get the fix in CU7 or are we going to have to upgrade to Spring?

Thanks.

**Comment by KennieNP** [comment]
You can mitigate the issue in the following way: 

Set NetFx40_LegacySecurityPolicy server configuration to true in production. This will get rid of the perf issue, but you cannot publish/debug AL.

If you need to publish/debug, set NetFx40_LegacySecurityPolicy server configuration to false while you do it. Reports will run slow while you debug/publish. When you are done, switch the setting back to true.

The server setting can be changed dynamically without the need for a server restart

**Comment by jimmymcp** [comment]
Thanks for the reply Kennie. We're not seeing a performance improvement though. To confirm, we've

- Added <NetFx40_LegacySecurityPolicy enabled="true" /> to Nav.Server.exe.config
- Restarted the service tier that we're connected to

Our last throw of the dice is that all service tiers sharing that config need to be stopped and restarted, although you said that wasn't necessary. It is still taking approx. 1 minute to generate a PDF attachment 

Are we missing anything?

**Comment by GeertvandenHout** [comment]
We still experience poor performance regarding generating a PDF in BC14 CU4. 
The problem occurs only with Custom Layout in the report layout selection. 
When pressing the button "Email Confirmation" on a sales order the email popup takes 25 seconds to generate.
I've done some testing, RDLC (Build-in) Layout takes less then 2 seconds to generate the email popup.

**Comment by Petyun** [comment]
Same issue on BC15 RTM when we generating Pdf using Report.SaveAs and Custom Layout. 
30-60 sec to generate (with Build-in layout - 1-2 seconds)

**Comment by JulianTillmann** [comment]
we're also experiencing this on CU16 (Build 44656).

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
