### ISSUE TITLE
Can't use CaptionClass for the field in the tableExtension

### ISSUE THREAD

**Issue by RedFoxUA** [microsoft/AL#4617]
I created a simple table extension and added code:

>         field(23071639; "Received by Bank"; Boolean)
>         {
>             Caption = 'Payment received by %1';
>             CaptionClass = GetCaptionClass(FIELDNO("Received by Bank"));
>             InitValue = false;
>             DataClassification = SystemMetadata;
>         }

Next, function GetCaptionClass (and I think subsriber for CU42 is very simple and no need to write here):

>     local procedure GetCaptionClass(FieldNumber: Integer): Text[80];
>     var
>         CurrField: Record 2000000041;
>     begin
>         CurrField.GET(DATABASE::"General Ledger Setup", FieldNumber);
>         case FieldNumber of
>             FIELDNO("Received by Bank") :
>                 exit(STRSUBSTNO('98,%1', CurrField."Field Caption"));
>             else begin
>                 //do another stuff
>             end;
>         end;
>     end;

The result:
[2019-02-16 00:23:22.40] The request for path /DynamicsNAV110/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$DynamicsNAV110\source\TableExtension\TableExtension23071639.cs(57,21) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$DynamicsNAV110\source\TableExtension\TableExtension23071639.cs(57,54) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.TableExtension23071639' does not contain a definition for 'ALFieldNo' and no extension method 'ALFieldNo' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.TableExtension23071639' could be found (are you missing a using directive or an assembly reference?)

If I change the caption string from "Caption = 'Payment received by %1';" to "Caption = 'Payment received by 11';" the result is same.

_Question - what did I wrong?_

**Comment by kalberes** [comment]
Does this repro on the latest BC preview? Looks like a bug to me. It may have been fixed there.
We do not really handle Nav 11 issue in here.

For those you can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by SirBETE** [comment]
Just had the same issue on BC14.0 (Microsoft_Application_14.0.29537.31430), compiler 3.0.126610 when installing app on our service (BC 14.0 Onprem).
App build, app published on the service, but when I wanted to install it, I got the same error:
```
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\140\Server\MicrosoftDynamicsNavServer$NAV\apps\metadata\3\03\0354535E2D949DE834ED95F4B4BB5D88DC4A305EC2902D6CDE897EADE989D
23A.cs(169,117): error CS1061: 'TableExtension2048879' does not contain a definition for 'ALFieldNo' and no accessible extension method 'ALFieldNo' accepting a first argument of type 'TableExtension2048879' could be found (are you missing a using directive or an assembly reference?)
```
TableExtension2048879 is on SalesLine

Searching on that path in programdata, gave me 4 files: 2 xmls en 2cs files:
Searched in the cs file after ALFieldNo to get:
```
        public override string EvaluateCaptionClass(int fieldNo, out bool handled)
        {
            handled = true;
            this.EnsureGlobalVariablesInitialized();
            switch (fieldNo)
            {
                case 2048875:
                    return ALCompiler.ObjectToExactNavValue<NavText>(base.ParentObject.Invoke(34, new object[]{this.ALFieldNo(2048875)}));
            }

            handled = false;
            return string.Empty;
        }
```
Field 2048875 in that tableextension is
```
        field(2048875; NewUnitPrice; Decimal)
        {
            AutoFormatExpression = "Currency Code";
            AutoFormatType = 2;
            CaptionClass = GetCaptionClass(FIELDNO(NewUnitPrice));
            DataClassification = CustomerContent;
        }
```

The `EvaluateCaptionClass` let me to comment out the `CaptionClass` property with the dynamic caption from `GetCaptionClass`.
When I tried to reinstall this new app, I got the same error, but on another table.
So when I commented out all dynamic captions, the app installed successfully.

So it looks like dynamic captions, with aid of `GetCaptionClass` isn't working ...
However no compiler error.

[Krzysztof Bialowas blogged about captionclass](http://www.mynavblog.com/2019/05/14/where-is-the-whole-code-for-captionclass-now/)
I just read that, and shall try to explore further ...
Will keep you posted.

**Comment by SirBETE** [comment]
Colleague had the same error when compiling the app (same versions), and fixed it by putting `Rec.` before the `FIELDNO`.
`CaptionClass = GetCaptionClass(Rec.FIELDNO(NewUnitPrice));`

Didn't had time yet to re-install the app with this fix.
(just wanted to post the update)

**Comment by SirBETE** [comment]
@kalberes 
Still having this error on BC15, (container "version": "15.1.37881.38709")
AL Language Compiler: 4.0.209944

Adding a field on sales line:
```
field(50000; x; Decimal)
        {
            AutoFormatExpression = "Currency Code";
            AutoFormatType = 2;
            CaptionClass = GetCaptionClass(FieldNo(x));
            Caption = 'x';
            DataClassification = CustomerContent;
            Editable = false;
        }
```

`The request for path /BC/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code 422. Reason: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\ED\ED56AB131C48BA3AC6AE80CCC4ECF83EC8DF36ED8BE0293534A421FD7F47759D.cs(57,125): error CS1061: 'TableExtension50020' does not contain a definition for 'ALFieldNo' and no accessible extension method 'ALFieldNo' accepting a first argument of type 'TableExtension50020' could be found (are you missing a using directive or an assembly reference?)`

**Comment by kalberes** [comment]
This is a bug that got fixed as far as I know. But I am not sure which update (15.3 ??)

**Comment by thloke** [comment]
Yes, this is fixed in 15.2 onwards. If this happens on update 15.2 or newer, definitely let us know. I'm going to close the issue for now since it's fixed.
