### ISSUE TITLE
Error AL0284 - Expected type __MissingTypeSymbol__ - Virtual table not recognized when publishing extension

### ISSUE THREAD

**Issue by legrlion** [microsoft/AL#5078]
Hi !

**Bug Description**
I get an error when trying to publish my extension to BC 140 OnPrem (not on Docker).
The virtual table used seems to not being recognized.

> SchemaUpdateMode=forcesync failed with code 422.
> Reason: Extension compilation failed
MyCodeunit.al(31,56): error AL0284: The type of the parameter 'TempAllObjWithCaption' on the event subscriber 'DimMgtOnAfterSetupObjectNoList' does not match the expected type '\_\_MissingTypeSymbol\_\_'.

It seems similar to [issue 4795](https://github.com/Microsoft/AL/issues/4795), but can't find any clue to solve mine.

**To Reproduce**
Subscribing to the following event, with AllObjWithCaption virtual table as parameter
```
[EventSubscriber(ObjectType::Codeunit, Codeunit::DimensionManagement, 'OnAfterSetupObjectNoList', '', true, true)]
local procedure DimMgtOnAfterSetupObjectNoList(var TempAllObjWithCaption: Record AllObjWithCaption temporary)
var
    AllObjWithCaption: Record AllObjWithCaption;
begin
    if AllObjWithCaption.Get(AllObjWithCaption."Object Type"::Table, Database::"Job Additional Status") then begin
        TempAllObjWithCaption := AllObjWithCaption;
        if TempAllObjWithCaption.Insert then;
    end;
end;
```
**Versions:**
 - AL Language: 3.0.126610
 - Business Central: 14.0.32600, OnPrem

**Additional information:**
 - Database was upgraded from NAV 5 SP1 to BC140 (v14.0.29530) (through NAV 2009 R2, NAV 2013 R2 and  - NAV 2017)
 - Database was upgraded from BC140 to BC140 CU1 (v14.0.32600).
 - No C/AL developments.
 - System and Test app republished with the right versions.
 - Symbols generated and "Enable loading application symbols at server startup " is true on ServerInstance (I know it's for AL-C/AL mixed developments only, but Download Symbols in VSCode wasn't working without this step)
 - Loading application symbols in VSCode works well

Thanks for the help !

**Comment by fvet** [comment]
We're facing the same issue. Having read through the blog of Freddy, we don't find a clue to solve our issues.

Situation is as follows:
- We need to set the 'Enable loading application symbols at server startup', since using 'Hybrid' / side-by-side development, BC 14 **on-prem**, **no Docker** involved
- We have to generate our application symbols on a BC database with GenerateSymbolRef. Compiling an object does actually updates the application.app / symbols, but seems to lose the symbols of the virtual tables.


[2019-06-28 13:58:56.86] The request for path /CONFIG_13/dev/apps?SchemaUpdateMode=forcesync failed with code 422. Reason: Extension compilation failed
src/Fixed%20Asset/PAG%20Deprec.%20by%20Period%20List.al(326,55): error AL0133: Argument 2: cannot convert from 'Record Date' to 'var __MissingTypeSymbol__'

**Comment by Ajef** [comment]
We're getting the same error after trying to publish NAV-Standard App after an Upgrade. We've also tried all the steps for side-by-side development to create symbol references in BC140 CU 01 on premise.

We receive the following error when publishing the NAV-Standard PayPalPaymentsStandard.app:
`Publish-NAVApp : Extension compilation failed
src/tables/TAB1070.al(200,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__'
src/tables/TAB1070.al(229,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__'
In Zeile:1 Zeichen:1 `

**Comment by fvet** [comment]
@thloke Any workaround we could use (except for deleting all references that cause the failure) or timing when we might expect a fix on MarketPlace? We no longer succeed in publishing our extensions...

**Comment by aacnsilva** [comment]
> We're getting the same error after trying to publish NAV-Standard App after an Upgrade. We've also tried all the steps for side-by-side development to create symbol references in BC140 CU 01 on premise.
> 
> We receive the following error when publishing the NAV-Standard PayPalPaymentsStandard.app:
> `Publish-NAVApp : Extension compilation failed src/tables/TAB1070.al(200,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__' src/tables/TAB1070.al(229,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__' In Zeile:1 Zeichen:1 `

I have exactly the same problem.

**Comment by atoader** [comment]
We believe this has been fixed in the latest CU of the Spring release. Could you use the latest Docker image and see if the issue still happens?

**Comment by legrlion** [comment]
The issue was bypassed using another event.
Customer uses OnPremise and upgrade to latest CU is not planned at this time.
We will try this on latest Docker image when we have time available.

Thanks for the answer !

**Comment by kfuglsang** [comment]
Was this in fact solved in a CU?

I also hit this issue on an on-prem v14 where we do hybrid development.

**Comment by atoader** [comment]
@kfuglsang what version are you using? can you provide code to reproduce the issue?

**Comment by kfuglsang** [comment]
I'm on 14.0.29530

It's easy enough to reproduce by simply:
- Enable loading application symbols at server startup
- Create a dummy codeunit 50000 in C/AL while finsql is in generatesymbolreference=yes (this step seems to discard symbols of the virtual tables)
- Reference any virtual table from an AL extension and try to compile it

**Comment by jbakach** [comment]
Hi,

I have this problem too, and I can't change the build because customer is using the database and I have to upload a modification. How can we bypass this? Can someone please point us out?

Thanks.

**Comment by vitaliizz** [comment]
@atoader any update on this?
14.0.41862 (CU11 April 2020) - the issue is still there..

**Comment by atoader** [comment]
For versions other that the latest, please open a support request. As this issue is fixed in the latest version of the product, I will close the thread.
