### ISSUE TITLE
Callstack issue

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#5872]
Have been searching if this was asked/reported before but could not find.

When debugging in VSCode it seems that the callstack is not updated right. Maybe I am doing something wrong (I hope so it could be easily fixed).

**What is the case?**
When debugging my AL code the callstack is not always shown in full extend. I have added a number of screenshot that relate the run-through of the code, form first to last. As you can see it alternately shows the full stack or only the current statement. This quite annoying, not to say highly counterproductive.

Is this a known issue (only noted this last week) and is there a workaround?

Asking this question on yammer I learned that more people are experiencing this.

![image](https://user-images.githubusercontent.com/18466198/81647655-aae82080-942d-11ea-900a-0948017d2dc6.png)
![image](https://user-images.githubusercontent.com/18466198/81647673-b1769800-942d-11ea-949e-7a9be3179f82.png)
![image](https://user-images.githubusercontent.com/18466198/81647686-b63b4c00-942d-11ea-92b3-43c278641808.png)

**Comment by lvanvugt** [comment]
BTW: Miljan Milosavljevic  also reported:

> Well there is also similar effect with "watch" as this block becomes not collapsable from time to tome. The Variables can be used instead.

**Comment by atoader** [comment]
@kalberes

**Comment by kalberes** [comment]
Have not seen the issue. What versions are we talking about? Many things have been changed mostly in workspace related debugger invocation for vsix version based on 16.1.

**Comment by lvanvugt** [comment]
Hi Kalman, this is any version including 16.1. Just checked it and the callstack sometimes shows the whole history and sometimes only the last called function.

**Comment by kalberes** [comment]
Hi Luc,
We had some issue with stacktrace handling that got fixed with the latest vsix release. But that was around performance around stack trace handling. Could you please try with this version.
Maybe the DAP (Debug Adapter Protocol) client part in VsCode may do this tricks if it gets information late.

**Comment by lvanvugt** [comment]
Kalman, I expect that my AL Language extension is always the latest form the gallery, so don't I have the one you point at already installed? If not, what need I do?
BTW: what version are you talking ablout?

**Comment by kalberes** [comment]
It is one in the gallery 5.0.280447. I think we released it on 05.28. But you logged the issue 22 days ago. 
Does this mean that you still see stack-traces being shortened?

**Comment by lvanvugt** [comment]
> Hi Kalman, this is any version including 16.1. Just checked it and the callstack sometimes shows the whole history and sometimes only the last called function.

This was yesterday after just checking on VSCode, so with the last version form the gallery. So it's still not working (fully) right.

**Comment by kalberes** [comment]
Do you maybe have a verifiable repro step? 
One thing you could do is set the al.editorServicesLogLevel to Verbose and somehow share  or expose the DebuggerServices.log file found in your vsix extension installation folder for al
C:\Users\<you>\.vscode\extensions<al extension instllation folder>

**Comment by lvanvugt** [comment]
> Do you maybe have a verifiable repro step?

Yes, I do (and sorry for the delay; had to find some time to do all the suggested things).

1. Take my _test automation example_ from GitHub: [Blocking Deletion of Warehouse Shipment Lines](https://github.com/fluxxus-nl/Test-Automation-Examples/tree/master/VSCode/Blocking%20Deletion%20of%20Warehouse%20Shipment%20Lines).
2. Build an deploy both App and Test extensions (you might need to adjust some settings in either app.json)
3. In **COD75650.UnblockDeletionEnabledFLX.al** set a break on 2nd [GIVEN] clause calling _CreateManuallyCreatedWarehouseShipmentFromReleasedSalesOrderWithOneLineWithRequireShipmentLocation_ in test **DeleteByUserWithNoAllowanceManuallyCreatedWhseShptLine**
4. Now run **DeleteByUserWithNoAllowanceManuallyCreatedWhseShptLinementLocation** in debugging session
5. Debugger should stop at breakpoint
6. Have a look at the call stack
![image](https://user-images.githubusercontent.com/18466198/85202527-35fae700-b307-11ea-93ad-d1a3302949a4.png)
7. Now step over **CreateManuallyCreatedWarehouseShipmentFromReleasedSalesOrderWithOneLineWithRequireShipmentLocation** (using F10)
8. Have another look at the call stack
![image](https://user-images.githubusercontent.com/18466198/85202605-d0f3c100-b307-11ea-9ada-2dce63a9d05f.png)

Clearly it's now showing the full stack. In most cases it does show the full call stack, but nnot always.

## Setting
- VSCode 1.46.1
- AL Language extension 5.0.288712

**Comment by lvanvugt** [comment]
> One thing you could do is set the al.editorServicesLogLevel to Verbose and somehow share or expose the DebuggerServices.log file found in your vsix extension installation folder for al
> C:\Users<you>.vscode\extensions

Tried this, but no differences. Find DebuggerServices.log file. It doesn't seem to have any meaningfull info around the time I have been running the debug session, being 2020-06-20 around 15:12.
[DebuggerServices.log](https://github.com/microsoft/AL/files/4807928/DebuggerServices.log)
attached.

**Comment by kalberes** [comment]
Thanks for the repro. I will try debugging it when time permits.

**Comment by mjmatthiesen** [comment]
It's a very common issue. You will see it all the time when debugging sandboxes - it's also inconsistent and at times will show the stack, in others it will not.

**Comment by kalberes** [comment]
As far as I know this has been fixed and will be available for the next release of the toolset.

**Comment by thloke** [comment]
Closing as this has been fixed in the 16.6 release.
