### ISSUE TITLE
Dependencies satisfied by higher version, but unpublish not allowed

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6009]
**Describe the bug**
If I have two apps. `Main 1.0` and `Library 1.0`. `Main 1.0` depends on `Library 1.0`. If I upgrade `Library 1.0` to `Library 1.1` I can not unpublish `Library 1.0` because it is required by `Main 1.0` although the dependency would still be satisfied by having `Library 1.1` present.

The error I get is this:
`The Extension cannot be unpublished because it is required by the following apps: <...>`

**To Reproduce**
1. Publish & install `Library 1.0`
2. Publish & install `Main 1.0` that has a dependency on `Library 1.0`
3. Publish & install `Library 1.1`
4. Try to unpublish `Library 1.0`: this step fails

**Expected behavior**
I expect `Library 1.0` to be able to unpublish without problems since - following the principles of minimum version, no breaking changes and backward-compatibility - `Library 1.1` must be fully compatible with `Library 1.0` and as such `Main 1.0` does no longer need `Library 1.0` because `Library 1.1` is there.

**5. Versions:**
 - AL Language: v5.0.288712
 - Business Central Platform: 16.0.14073.14195
 - Business Central Application: 16.3.14085.14363

**Comment by qutreson** [comment]
Hi @hemisphera, how are you publish/unpublish extensions? Are you doing this using the powershell cmdlets or from the extension management page?

I have tried reproducing this issue on our latest master without success with the following steps:
1. Publish, sync and install Library 1.0
2. Publish, sync and install Main 
3. Publish and sync Library 1.1
4. Uninstall Library 1.0 and Main 1.0
5. Upgrade Library 1.0 to 1.1 (with Start-NAVAppDataUpgrade)
6. Install Main 1.0 (at this point Library 1.0 is published but not installed, Main and Library 1.1 are installed).
7. Unpublish Library 1.0.

I also tried from VS Code and could not reproduce it either

**Comment by hemisphera** [comment]
I actually discovered just now that there is something more to it. Runtime packages play a part here. Here's exactly how to reproduce this

1. Deploy `lib 1.0` as a runtime package to the service via PowerShell
2. Deploy `main 1.0` as a runtime package to the service via Powershell 
3. Deploy `lib 1.1` through VSCode. This obviously does not work exactly because at this point I have two versions of `lib` installed and VSCode does not know how to handle that. This is a common issue I face and I usually just resolve it by "manually" running `Sync-NAVApp` a.s.o. through Powershell on `lib 1.1`.
1. However, if I now try to unpublish `lib 1.0` I run into the problem I described initially.

**Comment by qutreson** [comment]
What happens if you also install the extension after step 3? From your comment it looks like the library version 1.1 is published and synced but not installed, while library 1.0 is still installed. 

Get you run Get-NavAppInfo to give us the status (published/installed/sync) of the extensions before step 4?

**Comment by hemisphera** [comment]
Sorry for not being clearer. In step 3 I actually **publish**, **sync** and **install** (Start-NAVAppDataUpgrade in this case) `lib 1.1`. So when I run "Get-NAVAppInfo" after step 3 I get the following results:

![image](https://user-images.githubusercontent.com/8897936/87292923-d3f66180-c501-11ea-9041-452ef3c0eda2.png)

Maybe I've figured it out - I already thought about scope as I reiterated today and you can see the the apps have been published in different scopes (Global vs. Tenant). I reckon this is the cause?

**Comment by mynhardt7** [comment]
> 
> 
> Sorry for not being clearer. In step 3 I actually **publish**, **sync** and **install** (Start-NAVAppDataUpgrade in this case) `lib 1.1`. So when I run "Get-NAVAppInfo" after step 3 I get the following results:
> 
> ![image](https://user-images.githubusercontent.com/8897936/87292923-d3f66180-c501-11ea-9041-452ef3c0eda2.png)
> 
> Maybe I've figured it out - I already thought about scope as I reiterated today and you can see the the apps have been published in different scopes (Global vs. Tenant). I reckon this is the cause?

I encountered the same issue. Looks like it is an issue with Global vs Tenant.

**Comment by qutreson** [comment]
@hemisphera - Coming back to this issue after a long time.... Is this still something that you are experiencing on newer Business Central versions? Is it still impacting you? A lot has changed regarding how the server handle extension scopes since this was logged, so it might have been fixed already.

**Comment by erolkunman** [comment]
**Yes this is still an issue** at least OnPrem (BC23.4 W1). 

For example I have installed app A with PowerShell long time ago and that app is dependant on app B (also installed with PowerShell).
Now I publish (to test environment) a new version of app B from VSCode therefore I have now:
App B, version 1, Scope Global, Not installed
App B, version 2, Scope Tenant, Installed.

For some reason my App A is now automatically uninstalled and when I try to install it from BC I get error:
```
The extension A has a dependency on one or more extensions: App B, version 1
Do you want to install app A and all of its dependencies?
```

I select Yes and get error:
```
Cannot install the extension A published as Global application for the tenant default because it has one or more dependencies that are installed but have a conflicting version.
The following dependencies are not compatible with app A published as Global application: 
App B version 1 published as Global application

AL call stack: 
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionSilently line 4 - System Application by Microsoft
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionWithConfirmDialog line 27 - System Application by Microsoft
"Extension Details"(Page 2501)."Install - OnAction"(Trigger) line 2 - System Application by Microsoft
```

then when I try to unpublish the app B with version 1 (from PowerShell), I get also error:
`The Extension cannot be unpublished because it is required by the following apps: App A`

**So running around in error circles - how to solve?**

**Comment by thloke** [comment]
One restriction of app dependencies is that Global apps cannot depend on Tenant scoped apps. This means if you have:

- App Main depends on App Lib
- App Main published/installed in Global scope
- App Lib v1 published/installed in Global scope

Then you cannot install v2 of App Lib into Tenant scope, because that would mean Main (Global) would depend on Lib v2 (Tenant). You can however publish v2 of App Lib into Tenant scope, you just cannot install it.

Another way of thinking about it is that in the final installed graph of apps, if there is a case where a Global app would depend on a Tenant app, it is illegal.

So if you want to publish v2 of App Lib into Tenant scope (say, developing it in VSCode), you must either uninstall App Main, or publish into tenant scope a version of App Main first.

There might be a bug however in the "install App XYZ and all of its dependencies" functionality in the comment above. It is possible (I haven't checked) that when we do this, and there's a higher version of the dependency in Tenant scope, that we resolve against that instead of a version in Global scope.

Whether that's a bug we have capacity to address is another discussion. We'll need some use cases and scenarios blocked by it to determine that.

**Comment by thloke** [comment]
I'll put `Input Needed` on this to give time for feedback, and will close/accept later.

**Comment by itsme112358** [comment]
Hi! 
We have the same issue (on 25.1). To reproduce:
1. Install app A 1.0 globally
2. Install app B with dependency on app A using devendpoint (gets published in tenant default)
3. Install app A 1.1 using devendpoint (gets published in tenant default)
4. Publish, sync, upgrade app A 1.2 using "regular" Publish,sync,install/upgrade (Powershell) --> OK (at this point A 1.2 is published globally again, so the dependency criteria _should_ be met)
5. Unpublish app A 1.1 --> Fails with known error message `The Extension cannot be unpublished because it is required by the following apps: B...`

This is an issue that we cannot fix by ourselves without getting the apps. Get-NavAppinfo does not include infos about dependencies, so at install/unpublish time of app A we would need app B to get that information. We don't have app B because it is developed by a third party.

If after the unpublish of A fails we then Unpublish all the dependent apps B, listed in the error message (uninstall is not sufficient), we can unpublish app A. If we have app B we can republish it regardless of using global endpoint or developer endpoint. 
This proves that the version check during unpublish works differently than the version check during publish. This needs to be addressed.
