### ISSUE TITLE
Renaming enum value doesn't change initvalue of field using enum

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#6441]
**Describe the bug**
Renaming an enum value doesn't change the initvalue of field using enum

**To Reproduce**
Steps and to reproduce the behavior:
1. create enum
2. add value to enum (Calulation)
3. create field in table of type enum of 1.
4. set initvalue on the field
5. rename enumvalue (Calculation, fixing the typo)
6. Observe error `AL0522 Property value "Calulation" is not in the values for enum 'Source Type'.`

``` AL Code to reproduce the issue ```
```
enum 50000 "Source Type"
{
    Extensible = true;

    value(50000; "Calculation")
    {
        Caption = 'Calculation';
    }
```

```
        field(50000; "Source Type"; enum "Source Type")
        {
            DataClassification = CustomerContent;
            Caption = 'Source Type';
            InitValue = "Calulation";
        }
```

**Expected behavior**
Initvalue also renamed.

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.397164

 - Business Central: BE Business Central 17.2 (platform 17.0.19353.20441 + toepassing 17.2.19367.20601)

**Comment by thpeder** [comment]
Hi @SirBETE,
You have a typo in the InitValue property "Calulation" -> "Cal**c**ulation"

**Comment by SirBETE** [comment]
> Hi @SirBETE,
> You have a typo in the InitValue property "Calulation" -> "Cal**c**ulation"

Yes I know! That's why I renamed it!
Cuase I first made the enum value and the initvalue, but then noticed i got a typo, so I wanted to rename it, but noticed the InitValue didn't changed too

**Comment by NKarolak** [comment]
@thpeder Please reopen the issue - you did not read it properly ;-)

**Comment by SirBETE** [comment]
Or perhaps was my example and explanation bad :(

**Comment by NKarolak** [comment]
Well, I found it very clear. That's why I've interacted 😉

**Comment by JesperSchulz** [comment]
@thpeder, please take a second look at this issue. Thanks :-)

**Comment by thpeder** [comment]
My bad, I have taken a second look at it and I now understand that it was a simple rename that didn't kick in for the Initvalue.
That is obviously a bug and thanks a lot for report it!

**Comment by SirBETE** [comment]
Yes, correct! Ty! :D

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this issue about renaming enum values not updating InitValue — this was a good catch.

Since this was reported, enum value binding and property validation have received significant improvements, including diagnostic reporting for obsolete enum values in properties (PR 130207). We're closing this as part of a cleanup of older issues that we believe have been addressed.

If you still encounter this behavior on a current version, please don't hesitate to open a new issue with updated repro steps.

Thank you for helping us improve the AL developer experience!

**Comment by BertDeTemmerman** [comment]
Please reopen this one.
I've just tested it with version 16.3.2065053 and the bug still occured.

<img width="2002" height="524" alt="Image" src="https://github.com/user-attachments/assets/ca763b19-957c-4857-bb84-1b3c2b2f69c7" />
