### ISSUE TITLE
Disable ALxxx warnings with pragma not working

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#6708]
Duplicate of https://github.com/microsoft/AL/issues/6702
But as closed issues are not tracked anymore, I created a new one, I hope that's the correct approach.

I just tested the vsix of the insider artifact builds 18.4.27940.0 and 19.0.27938.0 as it should be fixed with Build 27937 according to Jespers comment (https://github.com/microsoft/AL/issues/6702#issuecomment-880518290) and I wanted to give early feedback. I used the Download-Artifacts command with a valid sasToken to get the artifacts..

However, the ALxxx and AAxxx Warnings still behave differently in my tests.
- #pragma warning disable AA0005 suppresses AA0005 errors
- #pragma warning disable AL0604 does NOT suppress AL0604 errors

Both AA0005 and AL0604 cops are by default a warning, but are set to errors using a ruleset. (see referenced issue)

Expected behaviour:
#pragma warning disable AL0604 (and all other ALxxx rules) suppresses AL0604 errors as well

Tested with:
```
#pragma warning disable AA0005 //This line suprresses the AA0005 error
codeunit 50100 "Test"
{
    Access = Internal;
    TableNo = Item;
    trigger OnRun()
    var
        Item: Record Item;
    begin
        If Item."No." = '' then begin //AA0005
            Item.Description := Format(CurrentDateTime());
        end;
    end;
}
```
```
#pragma warning disable AL0604 //This line does NOT suprresses the AL0604 error.
codeunit 50100 "Test"
{
    Access = Internal;
    TableNo = Item;
    trigger OnRun()
    var
        Item: Record Item;
    begin
        Copy(Item); //AL0604
    end;
}
```
The ruleset is shown in the referenced issue.

Have I simply tested too early and am missinterpreting the build numbers?

Best regards
David

**Comment by esbenk** [comment]
It is only fixed in 19. The build number refers to our platform components. It may take up to 2 weeks to reach the docker images.

**Comment by DavidFeldhoff** [comment]
Okay, just let me put it in my own words to make sure I understood it correctly.
I can currently download the artifact 19.0.27982.0 with the following command
```
$artifactUrl = Get-BCArtifactUrl -storageAccount 'bcinsider' -type 'sandbox' -sasToken $sasToken
Download-Artifacts -artifactUrl $artifactUrl -includePlatform
```
Inside the folder `C:\bcartifacts.cache\sandbox\19.0.27982.0\platform\ModernDev\program files\Microsoft Dynamics NAV\180\AL Development Environment` I can find a `ALLanguage.vsix`. That one has currently the version 8.0.487599.
And you say that in that AL Language version the fix is NOT included, right? Because there I still have that issue.

I'm just a bit confused because the "artifact number" 19.0.27982.0 seems to be higher than the "build number" 27937 Jesper mentioned. But if the artifacts which we can download and the platform components you're mentioning are two different things, then it makes sense and I'll just wait a little bit longer to test it.

**Comment by atoader** [comment]
Hi David! The fix should be in version 8.0.490982 of the AL Language VSIX. Can you see if it is in the daily grop?

**Comment by DavidFeldhoff** [comment]
Hi Alex, using the commands above I currently get the v8.0.487599 in the 19.0.28081.0 artifact. That explains why my tests still failed.
![image](https://user-images.githubusercontent.com/53570297/126269586-7c535886-a120-470f-baeb-49d5cd4c6b1c.png)

So thanks for clarifying that the "platform build number" is **not** the one we can see in the artifacts which we can download, even if the build numbers are nearly the same. 

To avoid confusion, I'd appreciate if the AL Language version in which the fix is included is specified directly. It seems as @JesperSchulz wanted to add that one in his comment directly, but something failed. Maybe you can have a look at that?
You can close the issue, I'll test it if the correct AL Language version is available. 
![image](https://user-images.githubusercontent.com/53570297/126269832-c7f8bde6-5754-4e58-8a17-0e2d418ace07.png)

**Comment by atoader** [comment]
Thanks, David! We'll take a look at the missing VS Code Extension Version issue. Please reopen the issue if it is not fixed in v8.0.490982 of the AL Language extension
