### ISSUE TITLE
Microsoft.Data.SQLClient

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/AL#7406]
**1. Describe the bug**
While flipping from BC21 to BC22 we ran into an issue around the mentioned assembly. Of course I am aware that the platform has changed, but still it is something that is kind of a surprise to me.
While working/building against .netpackages from BC21 I have no issue to use the SQLClient components with its functions and properties. The moment I flip to BC22 it can still load the assembly (as it is part of the ServiceTier Folder) but I can no longer compile my code as it can't find some of the parameters or methods from within the assembly.

We checked the dlls with dotpeek and we can't really see a change besides the obvious: for .net fw 4.8 vs .net 6. 

So I do understand that we should not have those dlls in use at all  - and we are actively working on this to get rid of them - but still it is kind of a strange behavior of the platform, and due to some backwards compatibility topics:

**2. To Reproduce**
0. create two dev containers (to get .net 6 to work at least with bccontainerhelper > v5)
1. AL:Go
2. add a dotnet.al file with the following content

```
dotnet
{
    assembly("Microsoft.Data.SqlClient")
    {
        type("Microsoft.Data.SqlClient.SqlConnection"; SQLConnection) { }
        type("Microsoft.Data.SqlClient.SqlCommand"; SQLCommand) { }
        type("Microsoft.Data.SqlClient.SqlDataReader"; SQLDataReader) { }
        type("Microsoft.Data.SqlClient.SqlInfoMessageEventArgs"; SqlInfoMessageEventArgs) { }
    }
}
```

that should work - no matter what your target is BC22 or BC21. (remember to flip the al probing path and reload)

3. now add a codeunit.al with the following:
```
procedure ExampleOfMissingMethod()
var
        SQLDataReader: DotNet SqlDataReader;
begin
  // works with BC 21 and BC22 assembly:
  SQLDataReader.Close();
  // only with the BC21 assembly - BC22 will miss this Method:
  SQLDataReader.Dispose();
end;
```
Now start to flip around the AlProbing path. You will see that Close() is never an issue (so somewhat access to the assembly is given) while Dispose() is suddenly no more accessible to BC22. You get immediate feedback in VS Code about it missing. And this is going along for quite some other methods from within the dll.

So, this should give you an example of what happens. That somehow AL loses track of methods of the dot net component. 

**3. Expected behavior**
well, that it works as before ... or at least get an explanation why it is no longer working, will never work again or is an issue and gets fixed :)

**4. Actual behavior**
while loading an assembly it should not miss methods between two BC Versions (as the dlls is carrying them around)

**5. Versions:**

- AL Language: v11.0.787898
- Visual Studio Code: 1.78.2
- Business Central: BC21 - BC22 (onPrem/Docker)
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ X ] Search the issue repository to ensure you are reporting a new issue

* [ X ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ X ] Simplify your code around the issue to better isolate the problem

**Comment by tgb-sw** [comment]
We have the same issue.
For instance Microsoft.Data.SqlClient.SQLDataAdapter only shows these members (looks like members from base classes are missing)
![grafik](https://github.com/microsoft/AL/assets/13784396/43fa0184-ac87-42be-b2fd-7759c5f60a08)

Not sure whether this is a problem specific with the Microsoft.Data.SqlClient assembly, or a bug introduced with BC22 (testend with 22.1
Clarification would be very helpfull.

**Comment by KristofKlein** [comment]
> 

you might can help me out here a bit: we also tried to flip to Ole ... but we have issues to get it "instantiated". mind to share your "Connect_ConnectString_Open" routine?

**Comment by tgb-sw** [comment]
We used SQLDataAdapter to fill a SQLDataTable.
Unfortunately we do not use/try to call "Connect_ConnectString_Open"
Just replaced SQLDataAdapter wit OleDbDataAdapter and had no issues to get it instantiated

#if USEOLEDB
        SQLDataAdapter: DotNet OleDbDataAdapter;
#else
        SQLDataAdapter: DotNet SQLDataAdapter;
#endif
....
#if USEOLEDB
        SQLDataAdapter := SQLDataAdapter.OleDbDataAdapter(SQLQuery, SQLServer."Connection String");
#else
        SQLDataAdapter := SQLDataAdapter.SqlDataAdapter(SQLQuery, SQLServer."Connection String");
#endif

**Comment by KristofKlein** [comment]
too bad - brings me all back to square one: as there is right now no assembly that I could use to trigger my stored procedures on the SQL server within the framework for BC22. Which I could utelize correctly as also the OleDb was stripped down by MS in the Framework .net 6 ...

**Comment by PooyaKharamesh** [comment]
I am closing this issue as this issue is fixed in the upcoming version (22.x next minor or preview version).

**Comment by RaKuNbg** [comment]
Hi @KristofKlein, @tgb-sw 
can you confirm if this error has been fixed with BC22.3?
I have an app from an partner where I had the same issue and I'm still facing it after I updated my development container to BC22.3

**Comment by tgb-sw** [comment]
I can confirm, with BC22.3 using Microsoft.Data.SqlClient works fine

**Comment by mjvisintin** [comment]
I am using BC22.5 and this is still an issue for me as of 11/17/2023

**Comment by mjvisintin** [comment]
I just noticed that I have a Canadian Build and not a US build, so I wonder if that is making a difference as to why I am still having this issue....Version: CA Business Central 22.5 (Platform 22.0.60117.0 + Application 22.5.59966.60134)
